### ISSUE TITLE
minify.json.php is incredibly slow

### ISSUE THREAD

**Issue by bmcminn** [getify/JSON.minify#19]
Just ran into an issue where using `minify.json.php` in my application results in ~4+ seconds of processing time on my localhost server before the client renders the page. Removing `minify.json.php` from my application eliminates the issue and the client renders a page in ~380ms.

I will be looking further into this issue, just wanted to document it here and see if others have seen this problem?

**Comment by pradyunsg** [comment]
@getify If you get the time, please look at this.
