### ISSUE TITLE
Establish requirements for minifier ports

### ISSUE THREAD

**Issue by bmcminn** [getify/JSON.minify#20]
Wanted to start a conversation about establishing requirements for the `JSON.minify` core functionality and provide this outline in the README file.

As a minifier, I expect it will:
- remove inline `// ...` and multiline `/* ... */` comments

Though some people may come to expect it will also:
- strip trailing commas
  - `{ "foo": "bar", "foo2": "bar2", }`
- remove multiple commas
  - `{ "foo": "bar", , "foo2": "bar2" }`
- minifiy inline JSON data
  - `/* all my json data is inline >:D */{"this": "is just aweful..." // inline comment hell "please": "don't make me parse this :'("}`

---

Since the goal is to parse development quality JSON and not necessarily validate it, I think the following expectations should be established to help define test cases for current and future ports:
1. JSON should be relatively well formatted (Human readable is optional)
   - Would validate normally if comments were not embedded
   - No hard requirements regarding comma-first/comma-last notation
2. JSON should be multi-line
3. Inline comments should not precede JSON markup

**Comment by pradyunsg** [comment]
Let's carry the discussion forward?

------

I think if anything, JSON-minify should be handling commas, since if the use case we are aiming is of JSON in configuration files, edited by humans, then commas are definitely a nuisance.
