### ISSUE TITLE
Put different language implementations on different branches (Will break all other PRs)

### ISSUE THREAD

**Issue by pradyunsg** [getify/JSON.minify#23]
I had a small suggestion, that you put the implementations in separate branches, one for each language. This way, language-specific packaging can be easily done, in a single repository.

Just what I think.... :smile: 

PS: I will happily make a PR for solving #21 if this is done.

------
  - [x] Create a `base` branch from where someone can start work on a new language port. #25 
  - Make language branches off `base` and populate them.
    - [x] `node`
    - [x] `javascript`
    - [x] `php`
    - [x] `python` #26
    - [ ] `java` #27 
    - [x] `objective-c` #28 
  - [ ] Clean up `master` and update documentation.

------

**Comment by getify** [comment]
This is a good idea to improve organization.

But do you think that just separate folders could accomplish the same thing... that is, one top-level directory for each language, where everything (including build stuff, tests, etc) needed is per-folder?

**Comment by pradyun** [comment]
I considered that and this (I have 2 clones with either one this system ATM). But I think this makes life a bit easier as many packaging/distribution tools support installing branches, but support for sub-directory based organization is less likely, especially without a file for every language in the root directory.

**Comment by pradyun** [comment]
I considered both, in fact have 2 clones for both arrangements on my system right now, and I think this arrangement makes distribution a bit easier as many packaging/distribution tools support installing from repository branches, but support for a sub-directory of a repository is less likely, especially without a file for every language in the root directory which, in a way, defeats the purpose of the organization.

Plus, then it is also possible to have language-specific things that would work with branches (Like Travis CI Build for eg.).

BTW: I forgot to mention, I have arranged my fork like how proposed (with some minor changes possibly, like using an independent base branch (instead of forked from master) etc). This is how it would look like...

**Comment by pradyun** [comment]
Ping!

**Comment by getify** [comment]
Appreciate the ping. I haven't gotten around to this because there's still many fires above it on my list. But I would happily consider a PR. ;-)

**Comment by pradyun** [comment]
Well, I would have made a PR, but I can't think of a way to have PR's for so many branches...

**Comment by getify** [comment]
Seems like it might be a PR for the main repo, plus a PR for each new branch. Seems a bit unwieldy, but might actually be good to consider each one separately to make sure details are proper.

**Comment by pradyun** [comment]
Well, how do I propose a new branch with a PR?

**Comment by getify** [comment]
I may be mistaken, but I believe if you create a separate branch in your fork, and submit a PR, you can target a branch on the main repo besides master. May (likely) be that we need to create those empty branches on this repo first. If so, first compiling a list of what main repo branches (by name) should be created would be quite helpful. :)

**Comment by pradyun** [comment]
Well, looks like making empty branches on this repository is the way to go. List of branches:

 - `base`
 - `master`
 - `python`
 - `javascript`
 - `java`
 - `php`
 - `objective-c`

**Comment by getify** [comment]
what will go in `base` different from `master`? moreover, what will be in `master`?

also, we'll need `node` separate from `javascript`, right?

**Comment by pradyun** [comment]
> what will go in base different from master? 
I think of `base` as being a "base" for all the ports (to base their work off) [the name came organically].

> moreover, what will be in master?
Just some documentation (about the universal algorithm).

> also, we'll need node separate from javascript, right?
I'm not so sure of that, after-all whatever's there in JS should be packaged as well, right?

**Comment by getify** [comment]
It's unclear at this point what `base` would actually have. If you can be more specific, that might motivate it. At the moment, my inclination would be to put whatever you're thinking for `base` into the documentation in `master` as you suggest.

No, right now the `node` version is modularized whereas the straight JS version is stand-alone (more suitable for copy-n-paste inclusion in other libs). I think I would want to preserve that.

**Comment by pradyun** [comment]
My motivation behind having a `base` is to have a clear point from where someone can start work on a new language port. Having a clear point in the history and basing everything off that point will look nicer in history graphs as it won't mix language-specific history. 
Also, it will be one point in the history from which every language port will be based. It would need rebasing language branches every time a commit is made to the `base`, but that should be very rare anyway, as documentation should be in `master`.

---

On second thought, how exactly is a port to be PRed?
I mean, if we need to make a branch on this repository before making a new PR for a language, I don't see that as convenient, for anyone involved. While it seems to be out-weighed by the advantages of the re-organization, it's an interesting problem. Any ideas about this?

**Comment by pradyun** [comment]
On second thought, how exactly is a port to be PRed?
I mean, if we need to make a branch on this repository before making a new PR for a language, I don't see that as convenient, for anyone involved. While it seems to be out-weighed by the advantages of the re-organization, it's an interesting problem. Any ideas about this?

**Comment by getify** [comment]
Instinct reaction: I think if someone's going to contribute a whole new port of the lib, having them show up completely unannounced with a PR is less ideal than first asking in an issue, understanding design philosophy, discussion options, etc. In this case, we can then create a branch if it seems appropriate for such a PR.

**Comment by pradyun** [comment]
I agree, but then there's #24. (As a counter-argument for the sake of it)

**Comment by getify** [comment]
That sort of thing wouldn't have happened if the reorg had already been in place. Would it have prevented the contribution entirely? I doubt it. Is it *slightly* more effort on a contributor's part? Yep.

**Comment by pradyun** [comment]
Yes, I was gonna say that... 

Well then, looks like all that's left here is you making the required branches here and me sending the required PRs. Then discussion should move there...

**Comment by pradyun** [comment]
Well, I really need to sleep now...

**Comment by pradyun** [comment]
I'm back!

**Comment by getify** [comment]
I will try to find sometime this weekend to sit down and make the branches. :)

**Comment by pradyun** [comment]
Ping 2.0!

**Comment by getify** [comment]
OK, first step done... I've created the "base" branch, here:

https://github.com/getify/JSON.minify/tree/base

1. Please have a look at that content, see if you think it's appropriate and correct as a starting point.
2. Once we agree it's good to go, I will start making the language branches (I'll handle JS, node, and PHP, since I wrote those originally) by branching off "base".
3. Once we're happy with how that's gone, then I'll create the other language branches, and you can help set them up.
4. Finally, once there's agreement that all the language branches are in order, we can clean up master by removing all language files and introducing updates to the documentation about porting, etc.

Sound good?

**Comment by pradyun** [comment]
Yep!

**Comment by pradyun** [comment]
Is it fine to call the ports hosted in this repository as "official"?

**Comment by getify** [comment]
OK, so (1) is now done on the above list. (2) is next. I'll get to that ASAP. Sorry I'm so slow, juggling lots of things! :)

**Comment by getify** [comment]
> Is it fine to call the various language ports in this repository as "official"?

yep

**Comment by pradyun** [comment]
Added suggestion regarding reorganization: Use labels to categorize issues and PRs as "common", by language, "algorithm" etc. You can think up a better list. But thought this was worth a mention.

**Comment by pradyun** [comment]
Added a good looking task-list to the issue for branch-wise tracking purposes.

**Comment by pradyunsg** [comment]
Ping v2.0!

**Comment by getify** [comment]
@pradyunsg

Thanks again for staying on top of this. Update:

1. I've created and pushed branches to this repo for all the language ports as listed in the checklist above
2. I've set up the "javascript", "node", and "php" branches with code and tests, and moved those respective files out of master.
3. I've made you a contributor now.

I would certainly appreciate eyeballs and help making sure that stuff is correct, and also help doing the "python", "java", and "objective-c" branch files.

Please check how I did the "test suite" stuff in each of the branches so far. I'd like to keep something close'ish if possible for the other ports, though not strictly required ofc.

Hope that helps get things moving now. :)

**Comment by pradyunsg** [comment]
Things did move.. :smile:

**Comment by pradyunsg** [comment]
On a new thought... Should the PORTING.md be a part of the Wiki?

**Comment by getify** [comment]
I don't have a strong feeling either way. I don't know that the wiki adds any value that the base repo branch doesn't already have, but if there's some reason to move that way, I wouldn't mind.

**Comment by pradyunsg** [comment]
Ok!

**Comment by pradyunsg** [comment]
I'm putting the Java port on the side-line as `will-fix later` and writing relavant documentation for master branch.

**Comment by getify** [comment]
LGTM.

**Comment by pradyunsg** [comment]
Done! Yay!

**Comment by pradyunsg** [comment]
Just merged `java` PR.
