### ISSUE TITLE
`from` is a keyword in ES6

### ISSUE THREAD

**Issue by pradyunsg** [getify/JSON.minify#29]
From https://github.com/lukehoban/es6features#modules

> ```js
> // app.js
> import * as math from "lib/math";
> alert("2π = " + math.sum(math.pi, math.pi));
> ```

It is currently used as a variable name in javascript and node code and the variable should be renamed.

**Comment by getify** [comment]
This is not an issue because the `from` keyword is only contextual in an `import` statement. It's perfectly safe to use outside of `import` statements.

**Comment by pradyunsg** [comment]
Ooh, OK.

*new thing learnt*
