### ISSUE TITLE
exports doesn't work for node 5 in node-json-minify

### ISSUE THREAD

**Issue by fuzing** [getify/JSON.minify#32]
Hi Kyle:

Could you change the 'exports' to 'module.exports' so that it continues to work correctly in node-5.

Cheers,

PB

**Comment by getify** [comment]
I would happily accept a PR.

**Comment by fuzing** [comment]
Hi Kyle:

I would have done that, except the package pointed to at github from the
‘node-minify-json’ (at npmjs.com)  doesn’t appear to be the same…….

Is there another github link I should be using?

Cheers, and sorry for the confusion,

Peter B.

**Comment by fuzing** [comment]
Sorry - I mean ‘node-json-minify’ (not ‘node-minify-json’)

**Comment by getify** [comment]
@fuzing -- awhile back, this repo was reorganized to have each lang/env port on its own branch. you might want to look at the "node" branch:

https://github.com/getify/JSON.minify/tree/node

**Comment by pradyunsg** [comment]
@fuzing Please confirm this is now fixed.

**Comment by fuzing** [comment]
I have no idea .... Given that it was a one line fix and after putting in a
PR you came back with a 'no way', I pursued a completely different
solution.   Single line fixes should be easy....... Not impeded

**Comment by fuzing** [comment]
I just went to the node repo and it does appear that the single line in
question has been changed.  Next time it would be great if, when the author
(Kyle) suggests that I submit a PR, you grant it.  This very simple one
line fix could have been implemented in 30 seconds instead of the days it
took.

**Comment by getify** [comment]
@fuzing -- the question wasn't about the fix, but about where the fix should be implemented within the organization of the project. When I suggested you look at the node fork, it already had the fix you were asking for. It just hadn't yet been pushed out as a new npm release with a version bump. That was an oversight, not some attempt at "impeding" your progress. You might also have been able to see the status of that branch (with the code you wanted) and asked about bumping the version, or better yet, PR'ing it. That might have gotten it out a little quicker than the "days" it took (which was < 3, btw).

**Comment by pradyunsg** [comment]
@fuzing It wasn't the fix, but the fact that the PR was targeted at the wrong branch in the repository that was the issue.

The repository had been recently re-organized, which broke the node-module. I should have made it more clear in my comment on the relavant PR. The fact that the re-organization wasn't documented well (or at all?) did not help the situation either.

So, I guess I should apologize for being overly terse in the relavant PR comment.

Lesson Learnt: Be less terse with PR comments.

**Comment by pradyunsg** [comment]
As OP, @fuzing could you please confirm that this issue has indeed been fixed?

**Comment by fuzing** [comment]
Pradyun - thanks for your response……..  Yes it does appear fixed - thank
you.    Kyle, I didn’t mean to get into a pissing contest with you, so I
apologize if I came off a little abruptly.  I was just a little annoyed at
being bounced around for a single line code change that would have taken 10
seconds to fix …… I’m mindful of productivity.  Sorry.

**Comment by fuzing** [comment]
resolved

**Comment by getify** [comment]
Cheers, glad things are resolved. Sorry for the slow/miscommunications.

**Comment by fuzing** [comment]
No worries Kyle - I know you’re busy!  Thanks for your response.  Cheers, PB

PS. I’m back to using your solution (i.e. the npm variant), having
originally just pilfered your code and made the one line change (it’s
cleaner this way!).  Be well.
