### ISSUE TITLE
Version Badges

### ISSUE THREAD

**Issue by pradyunsg** [getify/JSON.minify#35]
Should we add version badges to the repository? 

If yes, where? 
- In the master's README.md  -- Most visible
- In language-specific README.md -- Easiest from organization point of view
- Both -- More work but Better than individual ones

Note: Should use http://shields.io/

**Comment by getify** [comment]
What version badges did you have in mind?

**Comment by pradyunsg** [comment]
npm, pypi. And any other distribution we have in future.

**Comment by getify** [comment]
Then I think those should go respectively on each branch's README. :)
