### ISSUE TITLE
Create gpg keys for java code signing

### ISSUE THREAD

**Issue by kag0** [getify/JSON.minify#37]
For the java port, code deployed to maven central (see #36) is required to be signed. To this end, a gpg key should be created for the organization. This key should be controlled by the maintainers of the organization, and can be securely added to a CI server for automated deployment.

**Comment by pradyunsg** [comment]
Out of my zone. I'm not going to neither in control of the CI server nor willing to handle the gpg key.

Deferred in entirety to @getify.

**Comment by kag0** [comment]
I've made up a [little guide](https://gist.github.com/kag0/fb6b7ce0816b77fe8349) for continuous deployment to maven central, it includes a section on gpg key creation and management.
