### ISSUE TITLE
Set repo up on CI server

### ISSUE THREAD

**Issue by kag0** [getify/JSON.minify#38]
Is there interest to have continuous integration set up for this repo? Different languages could have their own configurations and badges could be added to the README files. For maven in particular it would be useful to have CI set up to enable CD on PR merges.

**Comment by pradyunsg** [comment]
I'd say we should have this. I think @getify will have to enable it on this repository.

**Comment by getify** [comment]
1. I'm not at all familiar with what the CI setup is? Would appreciate any pointers/links.
2. Is this repo going to change enough to warrant that sort of process/setup overhead?

**Comment by pradyunsg** [comment]
> I'm not at all familiar with what the CI setup is? Would appreciate any pointers/links.

It's pretty simple. I'm +5 for using Travis CI. It's free and really neat.

For setting that up, there's 2 steps.
   1. Click that Sign Up button on http://travis-ci.org. Creates an account at Travis CI.
   2. Flip the relevant switch over at https://travis-ci.org/profile/getify .

Then Travis watches pushes on branches and runs build/test jobs according to a `.travis.yml` file.

> Is this repo going to change enough to warrant that sort of process/setup overhead?

I don't see it as an overhead but a helper, it's just saving us from doing a clone and running the tests on our machine.

For Python, I'd love to get some CI. :smile:
For Java, the changes @kag0 suggests make more sense with a CI. (correct me if I'm wrong)

Plus we get good-looking badges and status checks. :wink:

**Comment by kag0** [comment]
@pradyunsg beat me to the links :smile:

Travis is especially helpful for code that goes into central repositories (maven central or npm or whathaveyou) because it can be used to do CD, that way the central repo always has the latest version and one of the project maintainers doesn't have to do the update by hand.

**Comment by pradyunsg** [comment]
Ping @getify?
