### ISSUE TITLE
Evolution of the PHP branch

### ISSUE THREAD

**Issue by t1st3** [getify/JSON.minify#41]
As said in t1st3/php-json-minify#13, I made a duplicate of the PHP branch of this module some time ago. The project (t1st3/php-json-minify) has kind of evolved from then, bringing the following "goodies" to the original code:
1. being published on [Packagist](https://packagist.org)
2. being a class rather than a function (allowing namespaces, following [PSR-4 spec](http://www.php-fig.org/psr/psr-4/).
3. having tests run with PHPUnit
4. having auto-generated API docs with PHPDocumentor

Yet, the original function has not changed at all since the beginning, and is still kind of a copy/paste of @getify 's original work.

This issue is merely a proposal to integrate all that has been done on my fork to the Kyle's project. This has been suggested by @emahuni and I personnaly think all these changes belong to this project rather than to a fork. So this issue should be seen as an open discussion rather than an absolute need for change :)

I'm willing to submit some PRs for these, but before that, please tell me if those PRs would be worth a shot!

@getify , I love your work btw...

**Comment by pradyunsg** [comment]
Sounds good to me. Is there any use case which would be broken if your repository php-json-minify, is directly shifted to this repositories `php` branch?

**Comment by t1st3** [comment]
@pradyunsg 

1. being published on packagist requires `composer.json` to be adapted, since it references to the fork. Then, I don't know whether a non-default branch (here the `php` one) can be used on packagist, but here is some info about requiring non-deault branch: https://getcomposer.org/doc/05-repositories.md#vcs
2. being a class rather than a function would be a breaking change. This could be circumvented by creating a class in a separate file, which would just `include` the original function. The namespace of the class would also need to be changed, since it also references to the fork.
3. Since the namespace of the class should be modified, then, the test should be slightly modified too, in order to point to the newly-namespaced class.
4. API doc should also be generated against the newly-namespaced class.
