### ISSUE TITLE
Port in Perl

### ISSUE THREAD

**Issue by rcoscali** [getify/JSON.minify#47]
Hi 

I port it to perl in my github https://github.com/rcoscali/JSON.minify
git@github.com:rcoscali/JSON.minify.git
All tests available in JS are ok and I added one for my own case.

**Comment by getify** [comment]
Awesome. I looked at your "perl" branch on that repo, seems fine except that the README still talks about python. Can you update those instructions to be appropriate for perl? I've created the "perl" branch on this repo, now, so once you've made that update, just do a PR to that branch. Thanks!

**Comment by rcoscali** [comment]
Ok no problem :)

**Comment by rcoscali** [comment]
Done

**Comment by getify** [comment]
Great, please submit a PR to merge into the main repo's "perl" branch.

**Comment by rcoscali** [comment]
on its way ...
