### ISSUE TITLE
Port to Dart

### ISSUE THREAD

**Issue by andrewackerman** [getify/JSON.minify#49]
I've ported the code to Dart [over here](https://github.com/andrewackerman/JSON.minify/tree/dart). All the tests pass in Dart (which makes it usable in both server-side Dart and Flutter), and it cleanly transpiles to JS with the `dart2js` utility (though why anyone would want to do that instead of just using the JS library itself is beyond me).

**Comment by getify** [comment]
Is this still relevant and maintained? If not, I'll close out this issue.
