### ISSUE TITLE
Retain newlines in comments

### ISSUE THREAD

**Issue by HansWeltar** [getify/JSON.minify#5]
When running with strip-space=False it would be nice if newlines were retained.
Retaining newlines helps JSON errors being reported with the correct line numbers.
eg: "Missing , on line 1" should be  "Missing , on line 2" if the first line contains a comment.

Here's inpiration for a fix:

<pre>
@@ -44,9 +44,14 @@
             in_singleline_comment = True
         elif (match.group() == '\n' or match.group() == '\r') and not in_string and not in_multiline_comment and in_singleline_comment:
             in_singleline_comment = False
+            if not strip_space:
+                new_str.append("\n")
         elif not in_multiline_comment and not in_singleline_comment and (
              match.group() not in ['\n','\r',' ','\t'] or not strip_space):
                 new_str.append(match.group())
+        elif (in_multiline_comment or in_singleline_comment) and \
+            match.group() in ['\n','\r'] and not strip_space:
+                new_str.append(match.group())
     
     new_str.append(json[from_index:])
     return ''.join(new_str)
</pre>

**Comment by pradyunsg** [comment]
Bump.
