### ISSUE TITLE
Update Python readme

### ISSUE THREAD

**Issue by trolologuy** [getify/JSON.minify#51]
I think we could clarify in the readme, that the name to use to import the module should be `json_minify`.
Leading to:
`import json_minify`

**Comment by archiif** [comment]
It's actually:
```
from json_minify import json_minify
```
Otherwise you get an error, no idea why.

**Comment by getify** [comment]
Is something wrong with the metadata for the python package? Why isn't import clean and simple?

**Comment by getify** [comment]
Is this still relevant? If not, I'll close this issue.
