### ISSUE TITLE
why is slow in javascript project 

### ISSUE THREAD

**Issue by Tiramisupxl** [getify/JSON.minify#54]
The code is:
```
const fs = require('fs');
const path = require('path');
const minify = require('node-json-minify');

//读取广州地铁线路数据
let subwayJson = fs.readFileSync(path.join(__dirname, '../../public/static/ht/displays/subway.json'), 'utf-8');
let subwayData = minify(subwayJson);
fs.writeFileSync(path.join(__dirname, './subway1.json'), subwayData);
```
It take a long time to output the file

**Comment by getify** [comment]
how big is that `subway.json` file?

**Comment by Tiramisupxl** [comment]
> how big is that `subway.json` file?

it is 1.9MB

**Comment by getify** [comment]
that's pretty surprising. how long is it taking? a second? five seconds? longer?

**Comment by Tiramisupxl** [comment]
> that's pretty surprising. how long is it taking? a second? five seconds? longer?

I didn't keep track of the time, can I send you the json file?

**Comment by getify** [comment]
This is not a project I actively manage, so I'd prefer it be shared publicly here in case others might be able to take a look.

Can you upload the file to a service like https://justpaste.it/ or https://ctxt.io/ ?

**Comment by Tiramisupxl** [comment]
> This is not a project I actively maintain, so I'd prefer it be shared publicly here in case others might be able to take a look.
> 
> Can you upload the file to a service like https://justpaste.it/ or https://ctxt.io/ ?

Sorry to reply so late. I haved tried several times to upload the json file in the website which you recommend but I failed, Maybe my Internet environment  is bad. Anyway, Thank you for your kindness！

**Comment by getify** [comment]
Maybe try a public file share on a dropbox or google drive upload?
