### ISSUE TITLE
Also stip trailing commas

### ISSUE THREAD

**Issue by getify** [getify/JSON.minify#6]
In an effort to make JSON parsing a little more flexible, strip any trailing commas in objects or arrays.

**Comment by schrolli** [comment]
hi,

how about making this for all imlementations? i came up with the same code as @metafeather on my own, because this isn't in the repo yet. Are there any arguments against it?

**Comment by getify** [comment]
I have no arguments against it. Sounds like a good feature.

But I also don't have the expertise to do it in all the other languages. I can add it to the JS version, at least, and perhaps the PHP version. It's just lower on my priority list atm.

**Comment by JeanOlivier** [comment]
Is this still planned as a feature? It'd be a good QOL improvement for human-written json files.

**Comment by getify** [comment]
I'd accept PRs for implementing it, but I'm not actively developing on this repo so I don't have any plans myself to implement it.
